//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.04 at 03:10:13 PM CST 
//


package Metadata.Specifications.DDI.LifeCycle.physicalinstance;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;

import Metadata.Specifications.DDI.LifeCycle.reusable.ReferenceType;


/**
 * Provides a statistical summary of the data in the related file as a set of variable level and category level statistics. May refer to a set of statistics provided in another physical instance (for example if the same data is held in multiple storage formats) or if the summary statistics are held as a separate data set.
 * <p>
 * <p>Java class for StatisticalSummaryType complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="StatisticalSummaryType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{ddi:physicalinstance:3_2}StatisticalDataLocation" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;element ref="{ddi:physicalinstance:3_2}VariableStatistics"/&gt;
 *           &lt;element ref="{ddi:physicalinstance:3_2}VariableStatisticsReference"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StatisticalSummaryType", propOrder = {
        "statisticalDataLocation",
        "variableStatisticsOrVariableStatisticsReference"
})
public class StatisticalSummaryType {

    @XmlElement(name = "StatisticalDataLocation")
    protected List<StatisticalDataLocationType> statisticalDataLocation;
    @XmlElements({
            @XmlElement(name = "VariableStatistics", type = VariableStatisticsType.class),
            @XmlElement(name = "VariableStatisticsReference", type = ReferenceType.class)
    })
    protected List<Object> variableStatisticsOrVariableStatisticsReference;

    /**
     * Reference to a PhysicalInstance that describes a data file containing the summary and/or category statistics OR contains the statistics in-line as in the case of the same data stored as an ASCII file and as an ORACLE file where the summary and category statistics are listed only in one of the physical instance files.Gets the value of the statisticalDataLocation property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the statisticalDataLocation property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStatisticalDataLocation().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StatisticalDataLocationType }
     */
    public List<StatisticalDataLocationType> getStatisticalDataLocation() {
        if (statisticalDataLocation == null) {
            statisticalDataLocation = new ArrayList<StatisticalDataLocationType>();
        }
        return this.statisticalDataLocation;
    }

    /**
     * Gets the value of the variableStatisticsOrVariableStatisticsReference property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the variableStatisticsOrVariableStatisticsReference property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVariableStatisticsOrVariableStatisticsReference().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VariableStatisticsType }
     * {@link ReferenceType }
     */
    public List<Object> getVariableStatisticsOrVariableStatisticsReference() {
        if (variableStatisticsOrVariableStatisticsReference == null) {
            variableStatisticsOrVariableStatisticsReference = new ArrayList<Object>();
        }
        return this.variableStatisticsOrVariableStatisticsReference;
    }

}
