# ==============================================================================
# Stage 1: Build & Package
# Purpose: Compile source code and assemble build artifacts.
# Note   : Uses full JDK/SDK; discarded in final image
# ==============================================================================
FROM eclipse-temurin:11-jdk AS BUILD

# Set the working directory for the build stage
ENV APP_HOME=/usr/app/
WORKDIR $APP_HOME

# Copy the service source files
COPY server/ /usr/app/
# Run gradle clean and build
RUN /usr/app/gradlew project-service:clean project-service:build

# ==============================================================================
# Stage 2: Production Runtime
# Purpose: Minimal execution environment for running the application.
# Artifacts: Copies compiled WAR from the 'build' stage.
# ==============================================================================
FROM jetty:11.0.26-jre11

# Set user to root so logs store in previous location
USER root

# Working Directory
WORKDIR /home/incore

# Copy service war
COPY --from=BUILD /usr/app/project-service/build/libs/project-service.war /home/incore/lib/

# Copy service context to jetty webapps
COPY docker/project.xml /var/lib/jetty/webapps/

# create data directory mounting point
RUN mkdir /home/incore/data && mkdir /home/incore/data/incore_data

# Reset WORKDIR so jetty runs correctly
WORKDIR /var/lib/jetty

ENV JETTY_PORT 8888

EXPOSE 8888
CMD ["java", "-Djava.io.tmpdir=/home/incore/", "-jar", "/usr/local/jetty/start.jar", "jetty.http.port=8888"]
