FROM openjdk:8-jre

# TODO we could compile the service here so this works standalone

# install cron
RUN apt-get -qq -y update && \
  apt-get -qq -y install cron

# Working Directory
WORKDIR /home/incore
COPY server/data-service/build/libs/data-service.war /home/incore/lib/
COPY docker/data.xml /home/incore/conf/
COPY docker/incore.properties /home/incore/conf/
COPY docker/jetty-runner.jar /home/incore/lib/

# cron job
COPY clear_cache.sh /home/incore/clear_cache.sh
COPY clear_cache_cron /home/incore/clear_cache_cron

# Give execution rights on the cron job
RUN chmod 0644 /home/incore/clear_cache_cron

# Apply cron job
RUN crontab /home/incore/clear_cache_cron

# Create the log file
RUN touch /var/log/clear_cache_cron.log
RUN chmod go+w /var/log/clear_cache_cron.log

# create data directory mounting point
RUN mkdir /home/incore/data && mkdir /home/incore/data/incore_data

ENV JETTY_PORT 8080

EXPOSE 8080
CMD ["java", "-Xmx512m", "-Dincore.properties=conf/incore.properties", "-jar", "lib/jetty-runner.jar", "--port", "8888", "conf/data.xml"]

