# ==============================================================================
# Stage 1: Build & Package
# Purpose: Compile source code and assemble build artifacts.
# Note   : Uses full JDK/SDK; discarded in final image
# ==============================================================================
FROM eclipse-temurin:11-jdk AS BUILD

# Set the working directory for the build stage
ENV APP_HOME=/usr/app/
WORKDIR $APP_HOME

# Copy the service source files
COPY server* /usr/app/
# Run gradle clean and build
RUN ./gradlew hazard-service:clean hazard-service:build

# ==============================================================================
# Stage 2: Production Runtime
# Purpose: Minimal execution environment for running the application.
# Artifacts: Copies compiled WAR from the 'build' stage.
# ==============================================================================
FROM jetty:11.0.26-jre11

USER root

# install gdal-bin
RUN apt-get -qq -y update && \
  apt-get -qq -y install --no-install-recommends cron && \
  apt-get -qq -y install software-properties-common && \
  add-apt-repository -y ppa:ubuntugis/ppa && \
  apt-get install -qq -y gdal-bin && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

# Working Directory
WORKDIR /home/incore

# Copy service war
COPY --from=BUILD /usr/app/hazard-service/build/libs/hazard-service.war /home/incore/lib/

# Copy service context to jetty webapps
COPY docker/hazard.xml /var/lib/jetty/webapps/

COPY clear_cache.sh /home/incore/clear_cache.sh
COPY clear_cache_cron /home/incore/clear_cache_cron

# Give execution rights on the cron job
RUN chmod 0644 /home/incore/clear_cache_cron

# Apply cron job
RUN crontab /home/incore/clear_cache_cron

# Create the log file
RUN touch /var/log/clear_cache_cron.log
RUN chmod go+w /var/log/clear_cache_cron.log

# create data directory mounting point
RUN mkdir /home/incore/data && mkdir /home/incore/data/incore_data

# Reset WORKDIR so jetty runs correctly
WORKDIR /var/lib/jetty

ENV JETTY_PORT 8888

EXPOSE 8888
CMD ["sh", "-c", "cron && java -Djava.io.tmpdir=/home/incore/ -jar /usr/local/jetty/start.jar jetty.http.port=8888"]
