//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.04 at 03:10:13 PM CST 
//


package Metadata.Specifications.DDI.LifeCycle.reusable;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CategoryRelationCodeType.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CategoryRelationCodeType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *     &lt;enumeration value="Nominal"/&gt;
 *     &lt;enumeration value="Ordinal"/&gt;
 *     &lt;enumeration value="Interval"/&gt;
 *     &lt;enumeration value="Ratio"/&gt;
 *     &lt;enumeration value="Continuous"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 */
@XmlType(name = "CategoryRelationCodeType")
@XmlEnum
public enum CategoryRelationCodeType {


    /**
     * A relationship of less than, or greater than, cannot be established among the included categories. This type of relationship is also called categorical or discrete.
     */
    @XmlEnumValue("Nominal")
    NOMINAL("Nominal"),

    /**
     * The categories in the domain have a rank order.
     */
    @XmlEnumValue("Ordinal")
    ORDINAL("Ordinal"),

    /**
     * The categories in the domain are in rank order and have a consistent interval between each category so that differences between arbitrary pairs of measurements can be meaningfully compared.
     */
    @XmlEnumValue("Interval")
    INTERVAL("Interval"),

    /**
     * The categories have all the features of interval measurement and also have meaningful ratios between arbitrary pairs of numbers.
     */
    @XmlEnumValue("Ratio")
    RATIO("Ratio"),

    /**
     * May be used to identify both interval and ratio classification levels, when more precise information is not available.
     */
    @XmlEnumValue("Continuous")
    CONTINUOUS("Continuous");
    private final String value;

    CategoryRelationCodeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CategoryRelationCodeType fromValue(String v) {
        for (CategoryRelationCodeType c : CategoryRelationCodeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
