//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.04 at 03:10:13 PM CST 
//


package Metadata.Specifications.DDI.LifeCycle.reusable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A stack of LocationValueReferences to each of the locations of the specified PrimaryComponentLevel type that make up the Component Area. Includes a GeographicTime to allow for repetition for change over time.
 * <p>
 * <p>Java class for ComponentPartsType complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="ComponentPartsType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{ddi:reusable:3_2}LocationValueReference" minOccurs="0"/&gt;
 *         &lt;element ref="{ddi:reusable:3_2}GeographicTime" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ComponentPartsType", propOrder = {
        "locationValueReference",
        "geographicTime"
})
public class ComponentPartsType {

    @XmlElement(name = "LocationValueReference")
    protected ReferenceType locationValueReference;
    @XmlElement(name = "GeographicTime")
    protected DateType geographicTime;

    /**
     * Reference to the LocationValue of a basic building block of the composite area.
     *
     * @return possible object is
     * {@link ReferenceType }
     */
    public ReferenceType getLocationValueReference() {
        return locationValueReference;
    }

    /**
     * Sets the value of the locationValueReference property.
     *
     * @param value allowed object is
     *              {@link ReferenceType }
     */
    public void setLocationValueReference(ReferenceType value) {
        this.locationValueReference = value;
    }

    /**
     * The time period for which the LocationValues listed are a valid set.
     *
     * @return possible object is
     * {@link DateType }
     */
    public DateType getGeographicTime() {
        return geographicTime;
    }

    /**
     * Sets the value of the geographicTime property.
     *
     * @param value allowed object is
     *              {@link DateType }
     */
    public void setGeographicTime(DateType value) {
        this.geographicTime = value;
    }

}
