//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.04 at 03:10:13 PM CST 
//


package Metadata.Specifications.DDI.LifeCycle.reusable;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Describes the type of evaluation, completion date, evaluation process and outcomes of the ExPost Evaluation. Allows identification of the Evaluator via reference to and organization or individual and provides for the optional use of a controlled vocabulary to define the specific role of the evaluator.
 * <p>
 * <p>Java class for EvaluatorType complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="EvaluatorType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{ddi:reusable:3_2}EvaluatorReference"/&gt;
 *         &lt;element name="EvaluatorRole" type="{ddi:reusable:3_2}CodeValueType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EvaluatorType", propOrder = {
        "evaluatorReference",
        "evaluatorRole"
})
public class EvaluatorType {

    @XmlElement(name = "EvaluatorReference", required = true)
    protected ReferenceType evaluatorReference;
    @XmlElement(name = "EvaluatorRole")
    protected List<CodeValueType> evaluatorRole;

    /**
     * Reference to an Organization or Individual involved in performing the evaluation.
     *
     * @return possible object is
     * {@link ReferenceType }
     */
    public ReferenceType getEvaluatorReference() {
        return evaluatorReference;
    }

    /**
     * Sets the value of the evaluatorReference property.
     *
     * @param value allowed object is
     *              {@link ReferenceType }
     */
    public void setEvaluatorReference(ReferenceType value) {
        this.evaluatorReference = value;
    }

    /**
     * Gets the value of the evaluatorRole property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the evaluatorRole property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEvaluatorRole().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodeValueType }
     */
    public List<CodeValueType> getEvaluatorRole() {
        if (evaluatorRole == null) {
            evaluatorRole = new ArrayList<CodeValueType>();
        }
        return this.evaluatorRole;
    }

}
