//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.04 at 03:10:13 PM CST 
//


package Metadata.Specifications.DDI.LifeCycle.reusable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A basic data representation for computing systems and applications expressed as a tuple (attribute key, value). Attribute keys may or may not be unique.
 * <p>
 * <p>Java class for StandardKeyValuePairType complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="StandardKeyValuePairType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{ddi:reusable:3_2}AttributeKey"/&gt;
 *         &lt;element ref="{ddi:reusable:3_2}AttributeValue"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StandardKeyValuePairType", propOrder = {
        "attributeKey",
        "attributeValue"
})
public class StandardKeyValuePairType {

    @XmlElement(name = "AttributeKey", required = true)
    protected CodeValueType attributeKey;
    @XmlElement(name = "AttributeValue", required = true)
    protected CodeValueType attributeValue;

    /**
     * This key (sometimes referred to as a name) expressed as a string. Supports the use of an external controlled vocabulary which is the recommended approach.
     *
     * @return possible object is
     * {@link CodeValueType }
     */
    public CodeValueType getAttributeKey() {
        return attributeKey;
    }

    /**
     * Sets the value of the attributeKey property.
     *
     * @param value allowed object is
     *              {@link CodeValueType }
     */
    public void setAttributeKey(CodeValueType value) {
        this.attributeKey = value;
    }

    /**
     * The value assigned to the named Key expressed as a string. Supports the use of an external controlled vocabulary.
     *
     * @return possible object is
     * {@link CodeValueType }
     */
    public CodeValueType getAttributeValue() {
        return attributeValue;
    }

    /**
     * Sets the value of the attributeValue property.
     *
     * @param value allowed object is
     *              {@link CodeValueType }
     */
    public void setAttributeValue(CodeValueType value) {
        this.attributeValue = value;
    }

}
