//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.04 at 03:10:13 PM CST 
//


package Metadata.Specifications.DDI.LifeCycle.reusable;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UniquenessScopeType.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="UniquenessScopeType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Agency"/&gt;
 *     &lt;enumeration value="Maintainable"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 */
@XmlType(name = "UniquenessScopeType")
@XmlEnum
public enum UniquenessScopeType {


    /**
     * The element ID is unique within the scope of the agency/sub-agency designation.
     */
    @XmlEnumValue("Agency")
    AGENCY("Agency"),

    /**
     * The element ID is unique within the scope of the parent maintainable object ID.
     */
    @XmlEnumValue("Maintainable")
    MAINTAINABLE("Maintainable");
    private final String value;

    UniquenessScopeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static UniquenessScopeType fromValue(String v) {
        for (UniquenessScopeType c : UniquenessScopeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
