//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.04 at 03:10:13 PM CST 
//


package Metadata.Specifications.DDI.LifeCycle.datacollection;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import Metadata.Specifications.DDI.LifeCycle.reusable.CodeValueType;
import Metadata.Specifications.DDI.LifeCycle.reusable.ReferenceType;


/**
 * Describes the aggregation method and the variables used in the aggregation process. Identifies the method using an external controlled vocabulary and identifies the variables used either in-line or by reference to an existing description.
 * <p>
 * <p>Java class for AggregationType complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="AggregationType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{ddi:reusable:3_2}AggregationMethod" minOccurs="0"/&gt;
 *         &lt;choice&gt;
 *           &lt;element ref="{ddi:datacollection:3_2}AggregationVariables" minOccurs="0"/&gt;
 *           &lt;element ref="{ddi:datacollection:3_2}AggregationVariablesReference" minOccurs="0"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AggregationType", propOrder = {
        "aggregationMethod",
        "aggregationVariables",
        "aggregationVariablesReference"
})
public class AggregationType {

    @XmlElement(name = "AggregationMethod", namespace = "ddi:reusable:3_2")
    protected CodeValueType aggregationMethod;
    @XmlElement(name = "AggregationVariables")
    protected AggregationVariablesType aggregationVariables;
    @XmlElement(name = "AggregationVariablesReference")
    protected ReferenceType aggregationVariablesReference;

    /**
     * Identification of the type of aggregation method used. Supports the use of a controlled vocabulary. DDI strongly recommends the use of a controlled vocabulary.
     *
     * @return possible object is
     * {@link CodeValueType }
     */
    public CodeValueType getAggregationMethod() {
        return aggregationMethod;
    }

    /**
     * Sets the value of the aggregationMethod property.
     *
     * @param value allowed object is
     *              {@link CodeValueType }
     */
    public void setAggregationMethod(CodeValueType value) {
        this.aggregationMethod = value;
    }

    /**
     * Identifies the independent and dependent variables used in the aggregation process in-line.
     *
     * @return possible object is
     * {@link AggregationVariablesType }
     */
    public AggregationVariablesType getAggregationVariables() {
        return aggregationVariables;
    }

    /**
     * Sets the value of the aggregationVariables property.
     *
     * @param value allowed object is
     *              {@link AggregationVariablesType }
     */
    public void setAggregationVariables(AggregationVariablesType value) {
        this.aggregationVariables = value;
    }

    /**
     * A reference to an existing AggregationVariables description.
     *
     * @return possible object is
     * {@link ReferenceType }
     */
    public ReferenceType getAggregationVariablesReference() {
        return aggregationVariablesReference;
    }

    /**
     * Sets the value of the aggregationVariablesReference property.
     *
     * @param value allowed object is
     *              {@link ReferenceType }
     */
    public void setAggregationVariablesReference(ReferenceType value) {
        this.aggregationVariablesReference = value;
    }

}
