//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.04 at 03:10:13 PM CST 
//


package Metadata.Specifications.DDI.LifeCycle.datacollection;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import Metadata.Specifications.DDI.LifeCycle.reusable.CodeValueType;
import Metadata.Specifications.DDI.LifeCycle.reusable.IdentifiableType;
import Metadata.Specifications.DDI.LifeCycle.reusable.StructuredStringType;


/**
 * A basic structure for describing the methodology used for collecting data. In addition to a descriptive narrative, the methodology may be classified by a short term or external controlled vocabulary.
 * <p>
 * <p>Java class for DataCollectionMethodologyType complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="DataCollectionMethodologyType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{ddi:reusable:3_2}IdentifiableType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{ddi:datacollection:3_2}TypeOfDataCollectionMethodology" minOccurs="0"/&gt;
 *         &lt;element ref="{ddi:reusable:3_2}Description" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DataCollectionMethodologyType", propOrder = {
        "typeOfDataCollectionMethodology",
        "description"
})
public class DataCollectionMethodologyType
        extends IdentifiableType {

    @XmlElement(name = "TypeOfDataCollectionMethodology")
    protected CodeValueType typeOfDataCollectionMethodology;
    @XmlElement(name = "Description", namespace = "ddi:reusable:3_2")
    protected StructuredStringType description;

    /**
     * Allows for brief identification of the type of data collection methodology using an optional controlled vocabulary.
     *
     * @return possible object is
     * {@link CodeValueType }
     */
    public CodeValueType getTypeOfDataCollectionMethodology() {
        return typeOfDataCollectionMethodology;
    }

    /**
     * Sets the value of the typeOfDataCollectionMethodology property.
     *
     * @param value allowed object is
     *              {@link CodeValueType }
     */
    public void setTypeOfDataCollectionMethodology(CodeValueType value) {
        this.typeOfDataCollectionMethodology = value;
    }

    /**
     * Full description of the data collection methodology. Supports structured content and multiple language content.
     *
     * @return possible object is
     * {@link StructuredStringType }
     */
    public StructuredStringType getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     *
     * @param value allowed object is
     *              {@link StructuredStringType }
     */
    public void setDescription(StructuredStringType value) {
        this.description = value;
    }

}
