//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.04 at 03:10:13 PM CST 
//


package Metadata.Specifications.DDI.LifeCycle.reusable;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * Holds the name of the contributor, their role, and optional reference to the contributor as described within a DDI Organization scheme. Repeat this element for multiple creators.
 * <p>
 * <p>Java class for ContributorType complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="ContributorType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice maxOccurs="2"&gt;
 *         &lt;sequence&gt;
 *           &lt;element ref="{ddi:reusable:3_2}ContributorName"/&gt;
 *           &lt;element ref="{ddi:reusable:3_2}ContributorRole" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;/sequence&gt;
 *         &lt;element ref="{ddi:reusable:3_2}ContributorReference"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ContributorType", propOrder = {
        "contributorNameAndContributorRoleOrContributorReference"
})
public class ContributorType {

    @XmlElements({
            @XmlElement(name = "ContributorName", type = BibliographicNameType.class),
            @XmlElement(name = "ContributorRole", type = CodeValueType.class),
            @XmlElement(name = "ContributorReference", type = ReferenceType.class)
    })
    protected List<Object> contributorNameAndContributorRoleOrContributorReference;

    /**
     * Gets the value of the contributorNameAndContributorRoleOrContributorReference property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contributorNameAndContributorRoleOrContributorReference property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContributorNameAndContributorRoleOrContributorReference().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BibliographicNameType }
     * {@link CodeValueType }
     * {@link ReferenceType }
     */
    public List<Object> getContributorNameAndContributorRoleOrContributorReference() {
        if (contributorNameAndContributorRoleOrContributorReference == null) {
            contributorNameAndContributorRoleOrContributorReference = new ArrayList<Object>();
        }
        return this.contributorNameAndContributorRoleOrContributorReference;
    }

}
