//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.04 at 03:10:13 PM CST 
//


package Metadata.Specifications.DDI.LifeCycle.reusable;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

import Metadata.Specifications.DDI.LifeCycle.datacollection.DistributionDomainType;


/**
 * Means of describing Distributions as a representation so that they can be used as a response domain questions. Primarily used as a response domain in a QuestionGrid. In addition to the base of objects of a representation the structure provides the total value to be distributed between the objects and the number of decimal positions allowed within a response.
 * <p>
 * <p>Java class for DistributionRepresentationBaseType complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="DistributionRepresentationBaseType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{ddi:reusable:3_2}RepresentationType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="DistributionValue" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="decimalPositions" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DistributionRepresentationBaseType", propOrder = {
        "distributionValue"
})
@XmlSeeAlso({
        DistributionDomainType.class
})
public class DistributionRepresentationBaseType
        extends RepresentationType {

    @XmlElement(name = "DistributionValue", required = true)
    protected BigDecimal distributionValue;
    @XmlAttribute(name = "decimalPositions")
    protected BigInteger decimalPositions;

    /**
     * Gets the value of the distributionValue property.
     *
     * @return possible object is
     * {@link BigDecimal }
     */
    public BigDecimal getDistributionValue() {
        return distributionValue;
    }

    /**
     * Sets the value of the distributionValue property.
     *
     * @param value allowed object is
     *              {@link BigDecimal }
     */
    public void setDistributionValue(BigDecimal value) {
        this.distributionValue = value;
    }

    /**
     * Gets the value of the decimalPositions property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getDecimalPositions() {
        return decimalPositions;
    }

    /**
     * Sets the value of the decimalPositions property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setDecimalPositions(BigInteger value) {
        this.decimalPositions = value;
    }

}
