//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.04 at 03:10:13 PM CST 
//


package Metadata.Specifications.DDI.LifeCycle.reusable;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Describes specific instances of GeographicLocations associated with a specified GeographicLevel in a GeographicStructure. In addition to the standard name, level, and description, specifies the Geographic Level either by reference to an existing description in a GeographicStructure or by a textual description, identifies the authorization source for naming and coding identification a set of individual LocationValues.
 * <p>
 * <p>Java class for GeographicLocationType complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="GeographicLocationType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{ddi:reusable:3_2}VersionableType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{ddi:reusable:3_2}GeographicLocationName" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{ddi:reusable:3_2}Label" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{ddi:reusable:3_2}Description" minOccurs="0"/&gt;
 *         &lt;choice&gt;
 *           &lt;element ref="{ddi:reusable:3_2}GeographicLevelReference"/&gt;
 *           &lt;element ref="{ddi:reusable:3_2}GeographicLevelDescription"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element ref="{ddi:reusable:3_2}AuthorizedSource" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{ddi:reusable:3_2}LocationValue" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GeographicLocationType", propOrder = {
        "geographicLocationName",
        "label",
        "description",
        "geographicLevelReference",
        "geographicLevelDescription",
        "authorizedSource",
        "locationValue"
})
public class GeographicLocationType
        extends VersionableType {

    @XmlElement(name = "GeographicLocationName")
    protected List<NameType> geographicLocationName;
    @XmlElement(name = "Label")
    protected List<LabelType> label;
    @XmlElement(name = "Description")
    protected StructuredStringType description;
    @XmlElement(name = "GeographicLevelReference")
    protected ReferenceType geographicLevelReference;
    @XmlElement(name = "GeographicLevelDescription")
    protected StructuredStringType geographicLevelDescription;
    @XmlElement(name = "AuthorizedSource")
    protected List<AuthorizedSourceType> authorizedSource;
    @XmlElement(name = "LocationValue")
    protected List<LocationValueType> locationValue;

    /**
     * A name for the GeographicLocation. May be expressed in multiple languages. Repeat the element to express names with different content, for example different names for different systems.Gets the value of the geographicLocationName property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the geographicLocationName property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGeographicLocationName().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NameType }
     */
    public List<NameType> getGeographicLocationName() {
        if (geographicLocationName == null) {
            geographicLocationName = new ArrayList<NameType>();
        }
        return this.geographicLocationName;
    }

    /**
     * A display label for the GeographicLocation. May be expressed in multiple languages. Repeat for labels with different content, for example, labels with differing length limitations.Gets the value of the label property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the label property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLabel().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LabelType }
     */
    public List<LabelType> getLabel() {
        if (label == null) {
            label = new ArrayList<LabelType>();
        }
        return this.label;
    }

    /**
     * A description of the GeographicLocation. May be expressed in multiple languages and supports the use of structured content.
     *
     * @return possible object is
     * {@link StructuredStringType }
     */
    public StructuredStringType getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     *
     * @param value allowed object is
     *              {@link StructuredStringType }
     */
    public void setDescription(StructuredStringType value) {
        this.description = value;
    }

    /**
     * Reference to an existing GeographicLevel describing structural level to which these locations belong.
     *
     * @return possible object is
     * {@link ReferenceType }
     */
    public ReferenceType getGeographicLevelReference() {
        return geographicLevelReference;
    }

    /**
     * Sets the value of the geographicLevelReference property.
     *
     * @param value allowed object is
     *              {@link ReferenceType }
     */
    public void setGeographicLevelReference(ReferenceType value) {
        this.geographicLevelReference = value;
    }

    /**
     * A description of the GeographicLevel. May be expressed in multiple languages and supports the use of structured content.
     *
     * @return possible object is
     * {@link StructuredStringType }
     */
    public StructuredStringType getGeographicLevelDescription() {
        return geographicLevelDescription;
    }

    /**
     * Sets the value of the geographicLevelDescription property.
     *
     * @param value allowed object is
     *              {@link StructuredStringType }
     */
    public void setGeographicLevelDescription(StructuredStringType value) {
        this.geographicLevelDescription = value;
    }

    /**
     * An identifiable authorization source repeated for each identifying code type. This allows the codes to be used as representations for response domains and value representations by designating a specific set of locations and the code of an authorization source. An authorization source should differentiate between codes derived for different purposes within the same agency.Gets the value of the authorizedSource property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the authorizedSource property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAuthorizedSource().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AuthorizedSourceType }
     */
    public List<AuthorizedSourceType> getAuthorizedSource() {
        if (authorizedSource == null) {
            authorizedSource = new ArrayList<AuthorizedSourceType>();
        }
        return this.authorizedSource;
    }

    /**
     * A location of the specified geographic level providing information on its name, identification codes, temporal and spatial coverage.Gets the value of the locationValue property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the locationValue property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLocationValue().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LocationValueType }
     */
    public List<LocationValueType> getLocationValue() {
        if (locationValue == null) {
            locationValue = new ArrayList<LocationValueType>();
        }
        return this.locationValue;
    }

}
