//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.04 at 03:10:13 PM CST 
//


package Metadata.Specifications.DDI.LifeCycle.reusable;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for KindOfDataTypeType.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="KindOfDataTypeType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Qualitative"/&gt;
 *     &lt;enumeration value="Quantitative"/&gt;
 *     &lt;enumeration value="Mixed"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 */
@XmlType(name = "KindOfDataTypeType")
@XmlEnum
public enum KindOfDataTypeType {


    /**
     * Narrative or descriptive accounts that may be subjected to interpretive analysis
     */
    @XmlEnumValue("Qualitative")
    QUALITATIVE("Qualitative"),

    /**
     * Numerical or coded data that may be subjected to statistical analysis
     */
    @XmlEnumValue("Quantitative")
    QUANTITATIVE("Quantitative"),

    /**
     * Both qualitative and quantitative data within the same collection.
     */
    @XmlEnumValue("Mixed")
    MIXED("Mixed");
    private final String value;

    KindOfDataTypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static KindOfDataTypeType fromValue(String v) {
        for (KindOfDataTypeType c : KindOfDataTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
