//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.04 at 03:10:13 PM CST 
//


package Metadata.Specifications.DDI.LifeCycle.reusable;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * Reference to the description of a MeasureDefinition in the NCube with a designation for its place in an array of measures if applicable. TypeOfObject should be set to MeasureDefinition.
 * <p>
 * <p>Java class for MeasureDefinitionReferenceType complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="MeasureDefinitionReferenceType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{ddi:reusable:3_2}ReferenceType"&gt;
 *       &lt;attribute name="arrayOrder" type="{http://www.w3.org/2001/XMLSchema}integer" default="0" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MeasureDefinitionReferenceType")
public class MeasureDefinitionReferenceType
        extends ReferenceType {

    @XmlAttribute(name = "arrayOrder")
    protected BigInteger arrayOrder;

    /**
     * Gets the value of the arrayOrder property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getArrayOrder() {
        if (arrayOrder == null) {
            return new BigInteger("0");
        } else {
            return arrayOrder;
        }
    }

    /**
     * Sets the value of the arrayOrder property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setArrayOrder(BigInteger value) {
        this.arrayOrder = value;
    }

}
