//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.04 at 03:10:13 PM CST 
//


package Metadata.Specifications.DDI.LifeCycle.reusable;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * This scheme contains a set of quality statements referenced by the metadata at different points in the lifecycle. In addition to the name, label, and description of the scheme, the structure supports the inclusion of another QualityStatementScheme by reference and a set of QualityStatement descriptions either in-line or by reference.
 * <p>
 * <p>Java class for QualityStatementSchemeType complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="QualityStatementSchemeType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{ddi:reusable:3_2}MaintainableType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{ddi:reusable:3_2}QualityStatementSchemeName" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{ddi:reusable:3_2}Label" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{ddi:reusable:3_2}Description" minOccurs="0"/&gt;
 *         &lt;element ref="{ddi:reusable:3_2}QualityStatementSchemeReference" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;element ref="{ddi:reusable:3_2}QualityStatement"/&gt;
 *           &lt;element ref="{ddi:reusable:3_2}QualityStatementReference"/&gt;
 *         &lt;/choice&gt;
 *         &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;element ref="{ddi:reusable:3_2}QualityStatementGroup"/&gt;
 *           &lt;element ref="{ddi:reusable:3_2}QualityStatementGroupReference"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QualityStatementSchemeType", propOrder = {
        "qualityStatementSchemeName",
        "label",
        "description",
        "qualityStatementSchemeReference",
        "qualityStatementOrQualityStatementReference",
        "qualityStatementGroupOrQualityStatementGroupReference"
})
public class QualityStatementSchemeType
        extends MaintainableType {

    @XmlElement(name = "QualityStatementSchemeName")
    protected List<NameType> qualityStatementSchemeName;
    @XmlElement(name = "Label")
    protected List<LabelType> label;
    @XmlElement(name = "Description")
    protected StructuredStringType description;
    @XmlElement(name = "QualityStatementSchemeReference")
    protected List<SchemeReferenceType> qualityStatementSchemeReference;
    @XmlElements({
            @XmlElement(name = "QualityStatement", type = QualityStatementType.class),
            @XmlElement(name = "QualityStatementReference", type = ReferenceType.class)
    })
    protected List<Object> qualityStatementOrQualityStatementReference;
    @XmlElements({
            @XmlElement(name = "QualityStatementGroup", type = QualityStatementGroupType.class),
            @XmlElement(name = "QualityStatementGroupReference", type = ReferenceType.class)
    })
    protected List<Object> qualityStatementGroupOrQualityStatementGroupReference;

    /**
     * A name for the scheme. May be expressed in multiple languages. Repeat the element to express names with different content, for example different names for different systems.Gets the value of the qualityStatementSchemeName property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the qualityStatementSchemeName property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQualityStatementSchemeName().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NameType }
     */
    public List<NameType> getQualityStatementSchemeName() {
        if (qualityStatementSchemeName == null) {
            qualityStatementSchemeName = new ArrayList<NameType>();
        }
        return this.qualityStatementSchemeName;
    }

    /**
     * A display label for the scheme. May be expressed in multiple languages. Repeat for labels with different content, for example, labels with differing length limitations.Gets the value of the label property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the label property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLabel().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LabelType }
     */
    public List<LabelType> getLabel() {
        if (label == null) {
            label = new ArrayList<LabelType>();
        }
        return this.label;
    }

    /**
     * A description of the content and purpose of the scheme. May be expressed in multiple languages and supports the use of structured content.
     *
     * @return possible object is
     * {@link StructuredStringType }
     */
    public StructuredStringType getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     *
     * @param value allowed object is
     *              {@link StructuredStringType }
     */
    public void setDescription(StructuredStringType value) {
        this.description = value;
    }

    /**
     * Inclusion of an existing QualityStatementScheme by reference.Gets the value of the qualityStatementSchemeReference property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the qualityStatementSchemeReference property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQualityStatementSchemeReference().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SchemeReferenceType }
     */
    public List<SchemeReferenceType> getQualityStatementSchemeReference() {
        if (qualityStatementSchemeReference == null) {
            qualityStatementSchemeReference = new ArrayList<SchemeReferenceType>();
        }
        return this.qualityStatementSchemeReference;
    }

    /**
     * Gets the value of the qualityStatementOrQualityStatementReference property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the qualityStatementOrQualityStatementReference property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQualityStatementOrQualityStatementReference().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link QualityStatementType }
     * {@link ReferenceType }
     */
    public List<Object> getQualityStatementOrQualityStatementReference() {
        if (qualityStatementOrQualityStatementReference == null) {
            qualityStatementOrQualityStatementReference = new ArrayList<Object>();
        }
        return this.qualityStatementOrQualityStatementReference;
    }

    /**
     * Gets the value of the qualityStatementGroupOrQualityStatementGroupReference property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the qualityStatementGroupOrQualityStatementGroupReference property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQualityStatementGroupOrQualityStatementGroupReference().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link QualityStatementGroupType }
     * {@link ReferenceType }
     */
    public List<Object> getQualityStatementGroupOrQualityStatementGroupReference() {
        if (qualityStatementGroupOrQualityStatementGroupReference == null) {
            qualityStatementGroupOrQualityStatementGroupReference = new ArrayList<Object>();
        }
        return this.qualityStatementGroupOrQualityStatementGroupReference;
    }

}
