//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.04 at 03:10:13 PM CST 
//


package Metadata.Specifications.DDI.LifeCycle.reusable;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * Describes the range of values used in the ranking system using Range and sets the number of times a single value can be repeated.
 * <p>
 * <p>Java class for RankingRangeType complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="RankingRangeType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{ddi:reusable:3_2}RangeType"&gt;
 *       &lt;attribute name="maximumRepetitionOfSingleValue" type="{http://www.w3.org/2001/XMLSchema}integer" default="1" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RankingRangeType")
public class RankingRangeType
        extends RangeType {

    @XmlAttribute(name = "maximumRepetitionOfSingleValue")
    protected BigInteger maximumRepetitionOfSingleValue;

    /**
     * Gets the value of the maximumRepetitionOfSingleValue property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getMaximumRepetitionOfSingleValue() {
        if (maximumRepetitionOfSingleValue == null) {
            return new BigInteger("1");
        } else {
            return maximumRepetitionOfSingleValue;
        }
    }

    /**
     * Sets the value of the maximumRepetitionOfSingleValue property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setMaximumRepetitionOfSingleValue(BigInteger value) {
        this.maximumRepetitionOfSingleValue = value;
    }

}
