//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.04 at 03:10:13 PM CST 
//


package Metadata.Specifications.DDI.LifeCycle.datacollection;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import Metadata.Specifications.DDI.LifeCycle.reusable.CommandCodeType;
import Metadata.Specifications.DDI.LifeCycle.reusable.ReferenceType;
import Metadata.Specifications.DDI.LifeCycle.reusable.StructuredStringType;
import Metadata.Specifications.DDI.LifeCycle.reusable.VersionableType;


/**
 * Processing instructions that pertain to data collection or data processing overall such as handling of non-response to questions, imputation practices, suppression rules, etc. General instructions should be listed separately to allow for referencing of specific processes.
 * <p>
 * <p>Java class for GeneralInstructionType complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="GeneralInstructionType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{ddi:reusable:3_2}VersionableType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{ddi:reusable:3_2}Description" minOccurs="0"/&gt;
 *         &lt;element ref="{ddi:reusable:3_2}CommandCode" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{ddi:datacollection:3_2}OverriddenCodeReference" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="isOverride" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GeneralInstructionType", propOrder = {
        "description",
        "commandCode",
        "overriddenCodeReference"
})
public class GeneralInstructionType
        extends VersionableType {

    @XmlElement(name = "Description", namespace = "ddi:reusable:3_2")
    protected StructuredStringType description;
    @XmlElement(name = "CommandCode", namespace = "ddi:reusable:3_2")
    protected List<CommandCodeType> commandCode;
    @XmlElement(name = "OverriddenCodeReference")
    protected ReferenceType overriddenCodeReference;
    @XmlAttribute(name = "isOverride")
    protected Boolean isOverride;

    /**
     * A description of the general instruction. May be expressed in multiple languages and supports the use of structured content.
     *
     * @return possible object is
     * {@link StructuredStringType }
     */
    public StructuredStringType getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     *
     * @param value allowed object is
     *              {@link StructuredStringType }
     */
    public void setDescription(StructuredStringType value) {
        this.description = value;
    }

    /**
     * Structured information used by a system to process the instruction.Gets the value of the commandCode property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the commandCode property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCommandCode().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CommandCodeType }
     */
    public List<CommandCodeType> getCommandCode() {
        if (commandCode == null) {
            commandCode = new ArrayList<CommandCodeType>();
        }
        return this.commandCode;
    }

    /**
     * Used when attribute of the containing GeneralInstruction isOverride equals true. This element provides the reference to the GeneralInstruction being overridden by the use of this instruction. For example a special confidentiality process used for a select set of variables rather than the normal process.
     *
     * @return possible object is
     * {@link ReferenceType }
     */
    public ReferenceType getOverriddenCodeReference() {
        return overriddenCodeReference;
    }

    /**
     * Sets the value of the overriddenCodeReference property.
     *
     * @param value allowed object is
     *              {@link ReferenceType }
     */
    public void setOverriddenCodeReference(ReferenceType value) {
        this.overriddenCodeReference = value;
    }

    /**
     * Gets the value of the isOverride property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public boolean isIsOverride() {
        if (isOverride == null) {
            return false;
        } else {
            return isOverride;
        }
    }

    /**
     * Sets the value of the isOverride property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setIsOverride(Boolean value) {
        this.isOverride = value;
    }

}
