//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.04 at 03:10:13 PM CST 
//


package Metadata.Specifications.DDI.LifeCycle.datacollection;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

import Metadata.Specifications.DDI.LifeCycle.reusable.CommandCodeType;


/**
 * Describes the ordering of items when not otherwise indicated. There are a set number of values for ItemSequenceType, but also a provision for describing an alternate ordering using a command language.
 * <p>
 * <p>Java class for SpecificSequenceType complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="SpecificSequenceType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{ddi:datacollection:3_2}ItemSequenceType"/&gt;
 *         &lt;element ref="{ddi:datacollection:3_2}AlternateSequenceType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SpecificSequenceType", propOrder = {
        "itemSequenceType",
        "alternateSequenceType"
})
@XmlSeeAlso({
        QuestionSequenceType.class
})
public class SpecificSequenceType {

    @XmlElement(name = "ItemSequenceType", required = true, defaultValue = "InOrderOfAppearance")
    @XmlSchemaType(name = "string")
    protected ItemSequenceTypeType itemSequenceType;
    @XmlElement(name = "AlternateSequenceType")
    protected CommandCodeType alternateSequenceType;

    /**
     * Identifies the type of sequence to use. Values include InOrderOfAppearance, Random, Rotate, and Other.
     *
     * @return possible object is
     * {@link ItemSequenceTypeType }
     */
    public ItemSequenceTypeType getItemSequenceType() {
        return itemSequenceType;
    }

    /**
     * Sets the value of the itemSequenceType property.
     *
     * @param value allowed object is
     *              {@link ItemSequenceTypeType }
     */
    public void setItemSequenceType(ItemSequenceTypeType value) {
        this.itemSequenceType = value;
    }

    /**
     * Information on the command used to generate an alternative means of determining sequence changes. If used, the ItemSequenceType should be "Other".
     *
     * @return possible object is
     * {@link CommandCodeType }
     */
    public CommandCodeType getAlternateSequenceType() {
        return alternateSequenceType;
    }

    /**
     * Sets the value of the alternateSequenceType property.
     *
     * @param value allowed object is
     *              {@link CommandCodeType }
     */
    public void setAlternateSequenceType(CommandCodeType value) {
        this.alternateSequenceType = value;
    }

}
