//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.05 at 03:37:15 PM CST 
//


package Metadata.Specifications.DDI.CodeBook;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for dimensnsType complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="dimensnsType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{ddi:codebook:2_5}baseElementType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{ddi:codebook:2_5}caseQnty" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{ddi:codebook:2_5}varQnty" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{ddi:codebook:2_5}logRecL" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{ddi:codebook:2_5}recPrCas" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{ddi:codebook:2_5}recNumTot" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dimensnsType", propOrder = {
        "caseQnties",
        "varQnties",
        "logRecLs",
        "recPrCas",
        "recNumTots"
})
@XmlRootElement(name = "dimensns")
public class Dimensns
        extends BaseElementType {

    @XmlElement(name = "caseQnty")
    protected List<SimpleTextType> caseQnties;
    @XmlElement(name = "varQnty")
    protected List<SimpleTextType> varQnties;
    @XmlElement(name = "logRecL")
    protected List<SimpleTextType> logRecLs;
    protected List<SimpleTextType> recPrCas;
    @XmlElement(name = "recNumTot")
    protected List<SimpleTextType> recNumTots;

    /**
     * Gets the value of the caseQnties property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the caseQnties property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCaseQnties().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SimpleTextType }
     */
    public List<SimpleTextType> getCaseQnties() {
        if (caseQnties == null) {
            caseQnties = new ArrayList<SimpleTextType>();
        }
        return this.caseQnties;
    }

    /**
     * Gets the value of the varQnties property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the varQnties property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVarQnties().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SimpleTextType }
     */
    public List<SimpleTextType> getVarQnties() {
        if (varQnties == null) {
            varQnties = new ArrayList<SimpleTextType>();
        }
        return this.varQnties;
    }

    /**
     * Gets the value of the logRecLs property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the logRecLs property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLogRecLs().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SimpleTextType }
     */
    public List<SimpleTextType> getLogRecLs() {
        if (logRecLs == null) {
            logRecLs = new ArrayList<SimpleTextType>();
        }
        return this.logRecLs;
    }

    /**
     * Gets the value of the recPrCas property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the recPrCas property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRecPrCas().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SimpleTextType }
     */
    public List<SimpleTextType> getRecPrCas() {
        if (recPrCas == null) {
            recPrCas = new ArrayList<SimpleTextType>();
        }
        return this.recPrCas;
    }

    /**
     * Gets the value of the recNumTots property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the recNumTots property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRecNumTots().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SimpleTextType }
     */
    public List<SimpleTextType> getRecNumTots() {
        if (recNumTots == null) {
            recNumTots = new ArrayList<SimpleTextType>();
        }
        return this.recNumTots;
    }

}
