//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.05 at 03:37:15 PM CST 
//


package Metadata.Specifications.DDI.CodeBook;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for rangeType complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="rangeType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{ddi:codebook:2_5}baseElementType"&gt;
 *       &lt;attribute name="UNITS" default="INT"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *             &lt;enumeration value="INT"/&gt;
 *             &lt;enumeration value="REAL"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="min" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="minExclusive" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="max" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="maxExclusive" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "rangeType")
@XmlRootElement(name = "range")
public class Range
        extends BaseElementType {

    @XmlAttribute(name = "UNITS")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String units;
    @XmlAttribute(name = "min")
    protected String min;
    @XmlAttribute(name = "minExclusive")
    protected String minExclusive;
    @XmlAttribute(name = "max")
    protected String max;
    @XmlAttribute(name = "maxExclusive")
    protected String maxExclusive;

    /**
     * Gets the value of the units property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getUNITS() {
        if (units == null) {
            return "INT";
        } else {
            return units;
        }
    }

    /**
     * Sets the value of the units property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setUNITS(String value) {
        this.units = value;
    }

    /**
     * Gets the value of the min property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getMin() {
        return min;
    }

    /**
     * Sets the value of the min property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setMin(String value) {
        this.min = value;
    }

    /**
     * Gets the value of the minExclusive property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getMinExclusive() {
        return minExclusive;
    }

    /**
     * Sets the value of the minExclusive property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setMinExclusive(String value) {
        this.minExclusive = value;
    }

    /**
     * Gets the value of the max property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getMax() {
        return max;
    }

    /**
     * Sets the value of the max property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setMax(String value) {
        this.max = value;
    }

    /**
     * Gets the value of the maxExclusive property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getMaxExclusive() {
        return maxExclusive;
    }

    /**
     * Sets the value of the maxExclusive property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setMaxExclusive(String value) {
        this.maxExclusive = value;
    }

}
