//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.05 at 03:37:15 PM CST 
//


package Metadata.Specifications.DDI.CodeBook;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;xhtml:div xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns="ddi:codebook:2_5" xmlns:dc="http://purl.org/dc/terms/" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:saxon="http://xml.apache.org/xslt" xmlns:xs="http://www.w3.org/2001/XMLSchema"&gt;&lt;xhtml:h1 class="element_title"&gt;Base Element SystemType&lt;/xhtml:h1&gt;&lt;xhtml:div&gt;&lt;xhtml:h2 class="section_header"&gt;Description&lt;/xhtml:h2&gt;&lt;xhtml:div class="description"&gt;This type forms the basis for all elements. Every element may contain the attributes defined the GLOBALS attribute group.&lt;/xhtml:div&gt;&lt;/xhtml:div&gt;&lt;/xhtml:div&gt;
 * </pre>
 * <p>
 * <p>
 * <p>Java class for baseElementType complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="baseElementType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attGroup ref="{ddi:codebook:2_5}GLOBALS"/&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "baseElementType")
@XmlSeeAlso({
        CitationType.class,
        OtherMat.class,
        Measure.class,
        Cohort.class,
        Dmns.class,
        NCube.class,
        GeoMap.class,
        Derivation.class,
        Invalrng.class,
        Range.class,
        Item.class,
        Valrng.class,
        Location.class,
        Var.class,
        NCubeGrp.class,
        VarGrp.class,
        DataDscr.class,
        PhysLoc.class,
        CubeCoord.class,
        DataItem.class,
        LocMap.class,
        Dimensns.class,
        RecDimnsn.class,
        RecGrp.class,
        FileStrc.class,
        FileTxt.class,
        FileDscr.class,
        OthrStdyMat.class,
        SetAvail.class,
        DataAccs.class,
        CodingInstructions.class,
        Sources.class,
        TargetSampleSize.class,
        FrameUnit.class,
        UseStmt.class,
        SampleFrame.class,
        DataColl.class,
        Method.class,
        Resource.class,
        DevelopmentActivity.class,
        StudyDevelopment.class,
        ExPostEvaluation.class,
        Standard.class,
        StandardsCompliance.class,
        QualityStatement.class,
        GeoBndBox.class,
        SumDscr.class,
        Subject.class,
        StdyInfo.class,
        StudyAuthorization.class,
        StdyDscr.class,
        ControlledVocabUsed.class,
        VerStmt.class,
        SerStmt.class,
        DistStmt.class,
        ProdStmt.class,
        RspStmt.class,
        TitlStmt.class,
        DocSrc.class,
        DocDscr.class,
        CodeBook.class,
        CatgryGrp.class,
        Mrow.class,
        Catgry.class,
        CatLevel.class,
        Point.class,
        Polygon.class,
        BoundPoly.class,
        Tbody.class,
        Row.class,
        Thead.class,
        Colspec.class,
        Tgroup.class,
        Table.class,
        AnlyInfo.class,
        AbstractTextType.class,
        Link.class,
        ExtLink.class
})
public abstract class BaseElementType {

    @XmlAttribute(name = "ID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    @XmlAttribute(name = "xml-lang")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String xmlLang;

    @XmlAttribute(name = "lang", namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "language")
    protected String lang;

    @XmlAttribute(name = "source")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String source;

    @XmlAttribute(name = "elementVersion")
    protected String elementVersion;

    @XmlAttribute(name = "elementVersionDate")
    protected String elementVersionDate;

    @XmlAttribute(name = "ddiLifecycleUrn")
    @XmlSchemaType(name = "anyURI")
    protected String ddiLifecycleUrn;

    @XmlAttribute(name = "ddiCodebookUrn")
    @XmlSchemaType(name = "anyURI")
    protected String ddiCodebookUrn;

    /**
     * Gets the value of the id property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the xmlLang property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getXmlLang() {
        return xmlLang;
    }

    /**
     * Sets the value of the xmlLang property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setXmlLang(String value) {
        this.xmlLang = value;
    }

    /**
     * Gets the value of the lang property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setLang(String value) {
        this.lang = value;
    }

    /**
     * Gets the value of the source property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSource() {
        if (source == null) {
            return "producer";
        } else {
            return source;
        }
    }

    /**
     * Sets the value of the source property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSource(String value) {
        this.source = value;
    }

    /**
     * Gets the value of the elementVersion property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getElementVersion() {
        return elementVersion;
    }

    /**
     * Sets the value of the elementVersion property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setElementVersion(String value) {
        this.elementVersion = value;
    }

    /**
     * Gets the value of the elementVersionDate property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getElementVersionDate() {
        return elementVersionDate;
    }

    /**
     * Sets the value of the elementVersionDate property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setElementVersionDate(String value) {
        this.elementVersionDate = value;
    }

    /**
     * Gets the value of the ddiLifecycleUrn property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDdiLifecycleUrn() {
        return ddiLifecycleUrn;
    }

    /**
     * Sets the value of the ddiLifecycleUrn property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDdiLifecycleUrn(String value) {
        this.ddiLifecycleUrn = value;
    }

    /**
     * Gets the value of the ddiCodebookUrn property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDdiCodebookUrn() {
        return ddiCodebookUrn;
    }

    /**
     * Sets the value of the ddiCodebookUrn property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDdiCodebookUrn(String value) {
        this.ddiCodebookUrn = value;
    }

}
