//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.05 at 03:37:15 PM CST 
//


package Metadata.Specifications.DDI.CodeBook;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for dataFingerprintType complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="dataFingerprintType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="digitalFingerprintValue" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="algorithmSpecification" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="algorithmVersion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="type" use="required"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *             &lt;enumeration value="data"/&gt;
 *             &lt;enumeration value="dataFile"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dataFingerprintType", propOrder = {
        "digitalFingerprintValue",
        "algorithmSpecification",
        "algorithmVersion"
})
@XmlRootElement(name = "dataFingerprint")
public class DataFingerprint {

    @XmlElement(required = true)
    protected String digitalFingerprintValue;
    protected String algorithmSpecification;
    protected String algorithmVersion;
    @XmlAttribute(name = "type", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String type;

    /**
     * Gets the value of the digitalFingerprintValue property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDigitalFingerprintValue() {
        return digitalFingerprintValue;
    }

    /**
     * Sets the value of the digitalFingerprintValue property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDigitalFingerprintValue(String value) {
        this.digitalFingerprintValue = value;
    }

    /**
     * Gets the value of the algorithmSpecification property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getAlgorithmSpecification() {
        return algorithmSpecification;
    }

    /**
     * Sets the value of the algorithmSpecification property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAlgorithmSpecification(String value) {
        this.algorithmSpecification = value;
    }

    /**
     * Gets the value of the algorithmVersion property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getAlgorithmVersion() {
        return algorithmVersion;
    }

    /**
     * Sets the value of the algorithmVersion property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAlgorithmVersion(String value) {
        this.algorithmVersion = value;
    }

    /**
     * Gets the value of the type property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setType(String value) {
        this.type = value;
    }

}
