//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.05 at 03:37:15 PM CST 
//


package Metadata.Specifications.DDI.CodeBook;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for frameUnitType complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="frameUnitType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{ddi:codebook:2_5}baseElementType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{ddi:codebook:2_5}unitType"/&gt;
 *         &lt;element ref="{ddi:codebook:2_5}txt" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="isPrimary" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "frameUnitType", propOrder = {
        "unitType",
        "txts"
})
@XmlRootElement(name = "frameUnit")
public class FrameUnit
        extends BaseElementType {

    @XmlElement(required = true)
    protected UnitType unitType;
    @XmlElement(name = "txt")
    protected List<Txt> txts;
    @XmlAttribute(name = "isPrimary")
    protected Boolean isPrimary;

    /**
     * Gets the value of the unitType property.
     *
     * @return possible object is
     * {@link UnitType }
     */
    public UnitType getUnitType() {
        return unitType;
    }

    /**
     * Sets the value of the unitType property.
     *
     * @param value allowed object is
     *              {@link UnitType }
     */
    public void setUnitType(UnitType value) {
        this.unitType = value;
    }

    /**
     * Gets the value of the txts property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the txts property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTxts().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Txt }
     */
    public List<Txt> getTxts() {
        if (txts == null) {
            txts = new ArrayList<Txt>();
        }
        return this.txts;
    }

    /**
     * Gets the value of the isPrimary property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public boolean isIsPrimary() {
        if (isPrimary == null) {
            return true;
        } else {
            return isPrimary;
        }
    }

    /**
     * Sets the value of the isPrimary property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setIsPrimary(Boolean value) {
        this.isPrimary = value;
    }

}
