//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.05 at 03:37:15 PM CST 
//


package Metadata.Specifications.DDI.CodeBook;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for sampleFrameType complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="sampleFrameType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{ddi:codebook:2_5}baseElementType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{ddi:codebook:2_5}sampleFrameName" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{ddi:codebook:2_5}labl" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{ddi:codebook:2_5}txt" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{ddi:codebook:2_5}validPeriod" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{ddi:codebook:2_5}custodian" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{ddi:codebook:2_5}useStmt" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{ddi:codebook:2_5}universe" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{ddi:codebook:2_5}frameUnit" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{ddi:codebook:2_5}referencePeriod" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{ddi:codebook:2_5}updateProcedure" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sampleFrameType", propOrder = {
        "sampleFrameNames",
        "labls",
        "txts",
        "validPeriods",
        "custodien",
        "useStmts",
        "universes",
        "frameUnits",
        "referencePeriods",
        "updateProcedures"
})
@XmlRootElement(name = "sampleFrame")
public class SampleFrame
        extends BaseElementType {

    @XmlElement(name = "sampleFrameName")
    protected List<StringType> sampleFrameNames;
    @XmlElement(name = "labl")
    protected List<Labl> labls;
    @XmlElement(name = "txt")
    protected List<Txt> txts;
    @XmlElement(name = "validPeriod")
    protected List<EventDateType> validPeriods;
    @XmlElement(name = "custodian")
    protected List<Custodian> custodien;
    @XmlElement(name = "useStmt")
    protected List<UseStmt> useStmts;
    @XmlElement(name = "universe")
    protected List<Universe> universes;
    @XmlElement(name = "frameUnit")
    protected List<FrameUnit> frameUnits;
    @XmlElement(name = "referencePeriod")
    protected List<EventDateType> referencePeriods;
    @XmlElement(name = "updateProcedure")
    protected List<SimpleTextType> updateProcedures;

    /**
     * Gets the value of the sampleFrameNames property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sampleFrameNames property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSampleFrameNames().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StringType }
     */
    public List<StringType> getSampleFrameNames() {
        if (sampleFrameNames == null) {
            sampleFrameNames = new ArrayList<StringType>();
        }
        return this.sampleFrameNames;
    }

    /**
     * Gets the value of the labls property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the labls property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLabls().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Labl }
     */
    public List<Labl> getLabls() {
        if (labls == null) {
            labls = new ArrayList<Labl>();
        }
        return this.labls;
    }

    /**
     * Gets the value of the txts property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the txts property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTxts().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Txt }
     */
    public List<Txt> getTxts() {
        if (txts == null) {
            txts = new ArrayList<Txt>();
        }
        return this.txts;
    }

    /**
     * Gets the value of the validPeriods property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the validPeriods property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getValidPeriods().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EventDateType }
     */
    public List<EventDateType> getValidPeriods() {
        if (validPeriods == null) {
            validPeriods = new ArrayList<EventDateType>();
        }
        return this.validPeriods;
    }

    /**
     * Gets the value of the custodien property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the custodien property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCustodien().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Custodian }
     */
    public List<Custodian> getCustodien() {
        if (custodien == null) {
            custodien = new ArrayList<Custodian>();
        }
        return this.custodien;
    }

    /**
     * Gets the value of the useStmts property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the useStmts property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUseStmts().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UseStmt }
     */
    public List<UseStmt> getUseStmts() {
        if (useStmts == null) {
            useStmts = new ArrayList<UseStmt>();
        }
        return this.useStmts;
    }

    /**
     * Gets the value of the universes property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the universes property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUniverses().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Universe }
     */
    public List<Universe> getUniverses() {
        if (universes == null) {
            universes = new ArrayList<Universe>();
        }
        return this.universes;
    }

    /**
     * Gets the value of the frameUnits property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the frameUnits property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFrameUnits().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FrameUnit }
     */
    public List<FrameUnit> getFrameUnits() {
        if (frameUnits == null) {
            frameUnits = new ArrayList<FrameUnit>();
        }
        return this.frameUnits;
    }

    /**
     * Gets the value of the referencePeriods property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the referencePeriods property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReferencePeriods().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EventDateType }
     */
    public List<EventDateType> getReferencePeriods() {
        if (referencePeriods == null) {
            referencePeriods = new ArrayList<EventDateType>();
        }
        return this.referencePeriods;
    }

    /**
     * Gets the value of the updateProcedures property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the updateProcedures property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUpdateProcedures().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SimpleTextType }
     */
    public List<SimpleTextType> getUpdateProcedures() {
        if (updateProcedures == null) {
            updateProcedures = new ArrayList<SimpleTextType>();
        }
        return this.updateProcedures;
    }

}
