//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.04 at 03:10:13 PM CST 
//


package Metadata.Specifications.DDI.LifeCycle.physicaldataproduct.proprietary;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

import Metadata.Specifications.DDI.LifeCycle.reusable.ReferenceType;


/**
 * Indicates that coded data should be treated as text, and references the definition of the text type as described in ManagedTextRepresentation. TypeOfObject should be set to ManagedTextRepresentation.
 * <p>
 * <p>Java class for CodedDataAsTextType complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="CodedDataAsTextType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{ddi:reusable:3_2}ReferenceType"&gt;
 *       &lt;attribute name="treatCodedDataAsText" type="{http://www.w3.org/2001/XMLSchema}boolean" fixed="true" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CodedDataAsTextType")
public class CodedDataAsTextType
        extends ReferenceType {

    @XmlAttribute(name = "treatCodedDataAsText")
    protected Boolean treatCodedDataAsText;

    /**
     * Gets the value of the treatCodedDataAsText property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public boolean isTreatCodedDataAsText() {
        if (treatCodedDataAsText == null) {
            return true;
        } else {
            return treatCodedDataAsText;
        }
    }

    /**
     * Sets the value of the treatCodedDataAsText property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setTreatCodedDataAsText(Boolean value) {
        this.treatCodedDataAsText = value;
    }

}
