//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.04 at 03:10:13 PM CST 
//


package Metadata.Specifications.DDI.LifeCycle.physicaldataproduct;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import Metadata.Specifications.DDI.LifeCycle.reusable.IdentifiableType;


/**
 * A description of the physical record segment as found in the data store. A logical record may be stored in one or more segments housed hierarchically in a single file or in separate data files. All logical records have at least one segment. Identifies the Key variable identifying the segment if the identifier exists in the record, a file name identifier if the segment identification is expressed as part of the file name (used when each segment is stored in a separate file), the order of this segment in relation to other physical segments as part of the logical record, and a flag indicating whether or not the physical segment contains a key.
 * <p>
 * <p>Java class for PhysicalRecordSegmentType complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="PhysicalRecordSegmentType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{ddi:reusable:3_2}IdentifiableType"&gt;
 *       &lt;sequence&gt;
 *         &lt;sequence&gt;
 *           &lt;element ref="{ddi:physicaldataproduct:3_2}KeyVariableReference" minOccurs="0"/&gt;
 *           &lt;element name="FileNameIdentification" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;/sequence&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="segmentOrder" type="{http://www.w3.org/2001/XMLSchema}integer" default="1" /&gt;
 *       &lt;attribute name="hasSegmentKey" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PhysicalRecordSegmentType", propOrder = {
        "keyVariableReference",
        "fileNameIdentification"
})
public class PhysicalRecordSegmentType
        extends IdentifiableType {

    @XmlElement(name = "KeyVariableReference")
    protected KeyVariableReferenceType keyVariableReference;
    @XmlElement(name = "FileNameIdentification")
    protected String fileNameIdentification;
    @XmlAttribute(name = "segmentOrder")
    protected BigInteger segmentOrder;
    @XmlAttribute(name = "hasSegmentKey")
    protected Boolean hasSegmentKey;

    /**
     * Reference to the Unique key variable for segment identification.
     *
     * @return possible object is
     * {@link KeyVariableReferenceType }
     */
    public KeyVariableReferenceType getKeyVariableReference() {
        return keyVariableReference;
    }

    /**
     * Sets the value of the keyVariableReference property.
     *
     * @param value allowed object is
     *              {@link KeyVariableReferenceType }
     */
    public void setKeyVariableReference(KeyVariableReferenceType value) {
        this.keyVariableReference = value;
    }

    /**
     * Gets the value of the fileNameIdentification property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFileNameIdentification() {
        return fileNameIdentification;
    }

    /**
     * Sets the value of the fileNameIdentification property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFileNameIdentification(String value) {
        this.fileNameIdentification = value;
    }

    /**
     * Gets the value of the segmentOrder property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getSegmentOrder() {
        if (segmentOrder == null) {
            return new BigInteger("1");
        } else {
            return segmentOrder;
        }
    }

    /**
     * Sets the value of the segmentOrder property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setSegmentOrder(BigInteger value) {
        this.segmentOrder = value;
    }

    /**
     * Gets the value of the hasSegmentKey property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public boolean isHasSegmentKey() {
        if (hasSegmentKey == null) {
            return false;
        } else {
            return hasSegmentKey;
        }
    }

    /**
     * Sets the value of the hasSegmentKey property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setHasSegmentKey(Boolean value) {
        this.hasSegmentKey = value;
    }

}
