//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.04 at 03:10:13 PM CST 
//


package Metadata.Specifications.DDI.LifeCycle.logicalproduct;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import Metadata.Specifications.DDI.LifeCycle.reusable.ReferenceType;


/**
 * ValueRange of variable indicating this record type, multiple entries allow for multiple valid values or ranges. Includes a reference to the variable an the specified related value. TypeOfObject should be set to Variabele.
 * <p>
 * <p>Java class for ConditionalVariableReferenceType complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="ConditionalVariableReferenceType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{ddi:reusable:3_2}ReferenceType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{ddi:logicalproduct:3_2}RelatedValue"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConditionalVariableReferenceType", propOrder = {
        "relatedValue"
})
public class ConditionalVariableReferenceType
        extends ReferenceType {

    @XmlElement(name = "RelatedValue", required = true)
    protected RelatedValueType relatedValue;

    /**
     * Use to specify the value of variable for which this is a case specification (i.e., GeoLevel in the example for Case Specification).
     *
     * @return possible object is
     * {@link RelatedValueType }
     */
    public RelatedValueType getRelatedValue() {
        return relatedValue;
    }

    /**
     * Sets the value of the relatedValue property.
     *
     * @param value allowed object is
     *              {@link RelatedValueType }
     */
    public void setRelatedValue(RelatedValueType value) {
        this.relatedValue = value;
    }

}
