//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.04 at 03:10:13 PM CST 
//


package Metadata.Specifications.DDI.LifeCycle.logicalproduct;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

import Metadata.Specifications.DDI.LifeCycle.reusable.ReferenceType;


/**
 * Reference to one or more categories for which the current category is a broader definition. Allows for a reference to the narrower category and the ability to define the relationship as a specialization or part. TypeOfObject should be set to Category.
 * <p>
 * <p>Java class for SubCategoryReferenceType complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="SubCategoryReferenceType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{ddi:reusable:3_2}ReferenceType"&gt;
 *       &lt;attribute name="typeOfSubCategory" type="{ddi:logicalproduct:3_2}SubCategoryType" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SubCategoryReferenceType")
public class SubCategoryReferenceType
        extends ReferenceType {

    @XmlAttribute(name = "typeOfSubCategory")
    protected SubCategoryType typeOfSubCategory;

    /**
     * Gets the value of the typeOfSubCategory property.
     *
     * @return possible object is
     * {@link SubCategoryType }
     */
    public SubCategoryType getTypeOfSubCategory() {
        return typeOfSubCategory;
    }

    /**
     * Sets the value of the typeOfSubCategory property.
     *
     * @param value allowed object is
     *              {@link SubCategoryType }
     */
    public void setTypeOfSubCategory(SubCategoryType value) {
        this.typeOfSubCategory = value;
    }

}
